name: bus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "app_assets/vahan_mitra.png"
  adaptive_icon_background: "#1656B9"
  adaptive_icon_foreground: "app_assets/vahan_mitra.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "app_assets/vahan_mitra.png"
    background_color: "#1656B9"
    theme_color: "#1656B9"

flutter:
  uses-material-design: true
  assets:
    - app_assets/
    - .env